module.exports = [
  {
    name: "pkgname",
    message: "What is the name of your brand new Node.js project?",
    default: "{outFolder}",
    filter: (val) => val.toLowerCase(),
  },
  {
    name: "description",
    message: "How would you describe the new APIs?",
    default: "An awesome API project",
  },
  {
    name: "name",
    message: "What is your full name?",
  },
  {
    name: "username",
    message: "What is your GitHub username?",
    default: "{gitUser.name}",
    filter: (val) => val.toLowerCase(),
    store: true,
  },
  {
    name: "email",
    message: "What is your Email?",
    default: "{gitUser.email}",
    filter: (val) => val.toLowerCase(),
    store: true,
  },
  {
    name: "website",
    message: "What is your website?",
    default: "{gitUser.website}",
    filter: (val) => val.toLowerCase(),
    store: true,
  },
  {
    name: "server",
    message: "Choose node.js server framework",
    type: "list",
    pageSize: 10,
    choices: [
      { name: "Express", value: "express" },
      { name: "Fastify", value: "fastify" },
      { name: "hapi", value: "hapi" },
      { name: "Koa", value: "koa" },
    ],
    default: "express",
  },
  {
    name: "useDb",
    message: "Do you want to use a Database?",
    type: "list",
    choices: [
      { name: "Yes", value: true },
      { name: "No", value: false },
    ],
    default: true,
  },
  {
    name: "db",
    message: "Choose one of the database management system",
    type: "list",
    when: (answers) => answers.useDb !== false,
    pageSize: 10,
    choices: [
      { name: "Postgres 🐘", value: "postgres" },
      { name: "MySQL 🐬", value: "mysql" },
    ],
    default: "none",
  },
  {
    name: "orm",
    message: "Would you like to use ORM?",
    type: "list",
    when: (answers) => answers.useDb !== false,
    pageSize: 10,
    choices: [
      { name: "Sequelize 🐘", value: "sequelize" },
      { name: "Typeorm 🐘", value: "typeorm" },
      { name: "I'd rather use raw database 🤷‍♂️", value: "none" },
    ],
    default: "none",
  },
  {
    name: "deploy",
    message: "How would you like to deploy your APIs?",
    type: "list",
    pageSize: 10,
    choices: [
      { name: "Docker 🐳", value: "docker" },
      { name: "I'd like to deploy it myself 🤓", value: "none" },
    ],
    default: "none",
  },
];
